
[Accessories]

	#Functionality of Idol Of Fertility.
	[Accessories.IdolOfFertility]
		#Is the effectiveness mechanic enabled?
		effectiveness = true
		#Maximum effectiveness bonus.
		#Range: -1.0 ~ 10.0
		maximum_effectiveness = 0.6
		#Chance for Idol of Fertility to drop from breeding.
		#Range: 0.0 ~ 1.0
		drop_chance = 0.005
		#Minimum effectiveness bonus.
		#Range: -1.0 ~ 10.0
		minimum_effectiveness = -0.6

		#Chance of having twins after breeding.
		[Accessories.IdolOfFertility.ExtraAnimalChance]
			#Normal Mode
			#Range: 0.0 ~ 1.0
			normal = 0.25
			#Expert Mode
			#Range: 0.0 ~ 1.0
			expert = 0.35
			#Master Mode
			#Range: 0.0 ~ 1.0
			master = 0.5

	#Functionality of Fisherman Emblem.
	[Accessories.FishermanEmblem]
		#Is the effectiveness mechanic enabled?
		effectiveness = true
		#Maximum effectiveness bonus.
		#Range: -1.0 ~ 10.0
		maximum_effectiveness = 0.6
		#Minimum effectiveness bonus.
		#Range: -1.0 ~ 10.0
		minimum_effectiveness = -0.6

		#Luck bonus when fishing.
		[Accessories.FishermanEmblem.Luck]
			#Normal Mode
			#Range: 1 ~ 100
			normal = 3
			#Expert Mode
			#Range: 1 ~ 100
			expert = 4
			#Master Mode
			#Range: 1 ~ 100
			master = 5

	#Functionality of Lucky Rock.
	[Accessories.LuckyRock]
		#Is the effectiveness mechanic enabled?
		effectiveness = true
		#Chance for End Ingot to drop from mining End Stone. (integration with Majrusz's Progressive Difficulty mod)
		#Range: 0.0 ~ 1.0
		end_ingot_chance = 0.01
		#Maximum effectiveness bonus.
		#Range: -1.0 ~ 10.0
		maximum_effectiveness = 0.6
		#Chance for Lucky Rock to drop from mining.
		#Range: 0.0 ~ 1.0
		drop_chance = 2.0E-4
		#Minimum effectiveness bonus.
		#Range: -1.0 ~ 10.0
		minimum_effectiveness = -0.6
		#Chance for End Shard to drop from mining End Stone. (integration with Majrusz's Progressive Difficulty mod)
		#Range: 0.0 ~ 1.0
		end_shard_chance = 0.1

		#Chance for extra loot when mining.
		[Accessories.LuckyRock.Chance]
			#Normal Mode
			#Range: 0.0 ~ 1.0
			normal = 0.03
			#Expert Mode
			#Range: 0.0 ~ 1.0
			expert = 0.045
			#Master Mode
			#Range: 0.0 ~ 1.0
			master = 0.06

	#Functionality of Secret Ingredient.
	[Accessories.SecretIngredient]
		#Is the effectiveness mechanic enabled?
		effectiveness = true
		#Maximum effectiveness bonus.
		#Range: -1.0 ~ 10.0
		maximum_effectiveness = 0.6
		#Minimum effectiveness bonus.
		#Range: -1.0 ~ 10.0
		minimum_effectiveness = -0.6

		#Duration bonus for all created potions.
		[Accessories.SecretIngredient.DurationBonus]
			#Normal Mode
			#Range: 0.0 ~ 5.0
			normal = 0.1
			#Expert Mode
			#Range: 0.0 ~ 5.0
			expert = 0.15
			#Master Mode
			#Range: 0.0 ~ 5.0
			master = 0.2

		#Amplifier bonus for all created potions.
		[Accessories.SecretIngredient.AmplifierBonus]
			#Normal Mode
			#Range: 0 ~ 10
			normal = 1
			#Expert Mode
			#Range: 0 ~ 10
			expert = 1
			#Master Mode
			#Range: 0 ~ 10
			master = 2

	#Functionality of Giant Seed.
	[Accessories.GiantSeed]
		#Is the effectiveness mechanic enabled?
		effectiveness = true
		#Maximum effectiveness bonus.
		#Range: -1.0 ~ 10.0
		maximum_effectiveness = 0.6
		#Chance for Giant Seed to drop from harvesting.
		#Range: 0.0 ~ 1.0
		drop_chance = 0.001
		#Minimum effectiveness bonus.
		#Range: -1.0 ~ 10.0
		minimum_effectiveness = -0.6

		#Chance for double loot when harvesting crops.
		[Accessories.GiantSeed.Chance]
			#Normal Mode
			#Range: 0.0 ~ 1.0
			normal = 0.25
			#Expert Mode
			#Range: 0.0 ~ 1.0
			expert = 0.4
			#Master Mode
			#Range: 0.0 ~ 1.0
			master = 0.55

	#Functionality of Certificate Of Taming.
	[Accessories.CertificateOfTaming]
		#Is the effectiveness mechanic enabled?
		effectiveness = true
		#Maximum effectiveness bonus.
		#Range: -1.0 ~ 10.0
		maximum_effectiveness = 0.6
		#Chance for Certificate of Taming to drop from taming animals.
		#Range: 0.0 ~ 1.0
		drop_chance = 0.01
		#Minimum effectiveness bonus.
		#Range: -1.0 ~ 10.0
		minimum_effectiveness = -0.6

		#Damage multiplier when the animal is tamed.
		[Accessories.CertificateOfTaming.DamageMultiplier]
			#Normal Mode
			#Range: 0.0 ~ 10.0
			normal = 0.15
			#Expert Mode
			#Range: 0.0 ~ 10.0
			expert = 0.2
			#Master Mode
			#Range: 0.0 ~ 10.0
			master = 0.25

		#Health multiplier when the animal is tamed.
		[Accessories.CertificateOfTaming.HealthMultiplier]
			#Normal Mode
			#Range: 0.0 ~ 10.0
			normal = 0.15
			#Expert Mode
			#Range: 0.0 ~ 10.0
			expert = 0.2
			#Master Mode
			#Range: 0.0 ~ 10.0
			master = 0.25

		#Jump height and speed multiplier when the horse is tamed.
		[Accessories.CertificateOfTaming.HorseBonusesMultiplier]
			#Normal Mode
			#Range: 0.0 ~ 10.0
			normal = 0.15
			#Expert Mode
			#Range: 0.0 ~ 10.0
			expert = 0.2
			#Master Mode
			#Range: 0.0 ~ 10.0
			master = 0.25

